# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cran: http://cran.rstudio.com
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
